fix "undefined reference to `__stack_chk_guard'"
The eglibc stage2 build fails with this error for some architectures,
because it tries to use libssp which is not built in gcc stage2. So tell
gcc that our libc will provide ssp support, which gcc cannot tell at
stage2, because eglibc stage1 was only headers.